[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "crappy"
dynamic = ["version"]
readme = "README.md"
description = "Command and Real-time Acquisition in Parallelized Python"
license = "GPL-2.0-or-later"
license-files = ["LICENSE"]
keywords = ["control", "command", "acquisition", "multiprocessing"]
dependencies = ["numpy>=2.0.0"]
requires-python = ">=3.10"
authors = [{name = "LaMcube", email = "antoine.weisrock@gmail.com"}]
maintainers = [{name = "Antoine Weisrock", email = "antoine.weisrock@gmail.com"}]
classifiers = ["Development Status :: 4 - Beta",
               "Intended Audience :: Science/Research",
               "Natural Language :: English",
               "Operating System :: OS Independent",
               "Programming Language :: Python :: 3.10",
               "Programming Language :: Python :: 3.11",
               "Programming Language :: Python :: 3.12",
               "Programming Language :: Python :: 3.13",
               "Programming Language :: Python :: 3.14",
               "Topic :: Scientific/Engineering",
               "Topic :: Software Development :: Build Tools",
               "Topic :: Software Development :: Embedded Systems"]

[project.urls]
Homepage = "https://github.com/LaboratoireMecaniqueLille/crappy"
Documentation = "https://crappy.readthedocs.io/en/latest/index.html"
Repository = "https://github.com/LaboratoireMecaniqueLille/crappy.git"
Issues = "https://github.com/LaboratoireMecaniqueLille/crappy/issues"
Download = "https://pypi.org/project/crappy/#files"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "crappy.__version__.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["crappy*"]
exclude = []
namespaces = false

[tool.setuptools.package-data]
crappy = ["tool/data/*",
          "tool/microcontroller.*",
          "tool/image_processing/kernels.cu"]
