# coding: utf-8

"""Headless checks for the camera configurator's backend-neutral core."""

import unittest
from typing import Any

import numpy as np

from crappy.camera.meta_camera import Camera
from crappy.camera.meta_camera.camera_setting import CameraBoolSetting
from crappy.tool.camera_config.configuration_core import CameraConfigCore


class CoreTestCamera(Camera):
  """Camera with no hardware or graphical dependencies."""

  frame: tuple[dict[str, Any], np.ndarray] | None = None

  def get_image(self) -> tuple[dict[str, Any], np.ndarray] | None:
    """Return a controllable frame without camera hardware."""

    return self.frame


class RecordingCore(CameraConfigCore):
  """Record core log messages without creating a GUI window."""

  def log(self, level: int, msg: str) -> None:
    """Discard messages generated by ordinary interactions."""

    ...


class TestConfigurationCore(unittest.TestCase):
  """Verify that core state and interactions work without a Tk root."""

  def test_initializes_settings_and_image_state(self) -> None:
    """The backend-neutral model can be constructed on its own."""

    camera = CoreTestCamera()
    setting = CameraBoolSetting('enabled', default=True)
    camera.settings['enabled'] = setting

    core = RecordingCore(camera, 30, None)

    self.assertEqual(core._setting_manager.settings, (setting,))
    self.assertIsNone(core.shape)
    self.assertIsNone(core.dtype)
    self.assertIsNone(core._img)
    self.assertEqual(core._max_freq, 30)

  def test_converts_image_and_updates_reticle_without_widgets(self) -> None:
    """Image conversion and pointer mapping update ordinary state only."""

    core = RecordingCore(CoreTestCamera(), None, None)
    image = np.arange(16, dtype=np.uint8).reshape(4, 4)
    core._cast_img(image)
    core._display_geometry.width = 40
    core._display_geometry.height = 40
    core._display_geometry.image_width = 40
    core._display_geometry.image_height = 40

    self.assertTrue(core._point_at(15, 25))
    self.assertEqual((core._display_state.reticle_x,
                      core._display_state.reticle_y,
                      core._display_state.reticle_value), (1, 2, 9))
    self.assertEqual(core._display_state.max_pixel, 15)
    self.assertTrue(core._zoom_at(20, 20, 1))
    self.assertGreater(core._display_state.zoom_percent, 100)

  def test_acquisition_transforms_and_reports_image_format(self) -> None:
    """The frame path and format reporting do not require a GUI loop."""

    camera = CoreTestCamera()
    camera.frame = ({}, np.ones((2, 3), dtype=np.uint8))
    core = RecordingCore(camera, None, lambda img: img.astype('uint16') * 2)

    self.assertTrue(core._acquire_image())
    self.assertEqual(core.shape, (2, 3))
    self.assertEqual(core.dtype, 'uint16')
    self.assertEqual(core._n_loops, 1)
    assert core._img is not None
    self.assertEqual(core._img.shape, (2, 3))

    camera.frame = None
    self.assertFalse(core._acquire_image())
    self.assertEqual(core._n_loops, 1)
