# coding: utf-8

"""
This example demonstrates the use of a Machine Block in the simplest possible
use case: driving a fake motor in speed mode. It does not require any specific
hardware to run, but necessitates the matplotlib Python module to be installed.

The Machine Block can drive one or more Actuators in speed or position mode,
based on the setpoints it receives from upstream Blocks. It can also retrieve
the current speed and/or position from the driven Actuators and send it to
downstream Blocks.

Here, a Machine Block drives a FakeDCMotor Actuator in speed. The setpoint is
generated by a Generator as a cyclic voltage value. A Grapher shows the
real-time dynamic behavior of the emulated DC motor.

After starting this script, observe how the speed of the DC motor evolves
according to the cyclic voltage setpoint. You can also adjust the parameters of
the setpoint (magnitude, frequency) and see how the emulated DC motor reacts.
This script ends after 20 seconds. Click the stop button to end the demo early.
"""

import crappy

if __name__ == '__main__':

  # This Generator generates the voltage command for the DC motor
  # It outputs a cyclic voltage and sends it to the Machine Block
  gen = crappy.blocks.Generator(
      # Generating a cyclic signal oscillating between 10V and -10V
      ({'type': 'Cyclic',
        'value1': -10,
        'condition1': 'delay=3',
        'value2': 10,
        'condition2': 'delay=3',
        'cycles': 3},),
      freq=50,  # Lowering the default frequency because it is just a demo
      cmd_label='voltage(V)',  # The output of the Generator is a voltage

      # Sticking to default for the other arguments
  )

  # This Machine Block drives a single Actuator, a FakeDCMotor
  # It drives it in speed mode based on the input voltage from the
  # Generator Block. The speed of the emulated DC motor is sent to the Grapher
  # via the 'speed(RPM)' label
  mot = crappy.blocks.Machine(
      ({'type': 'FakeDCMotor',  # The name of the Actuator to drive
        'cmd_label': 'voltage(V)',  # The label carrying the setpoint
        'mode': 'speed',  # Driving here in speed mode, not in position mode
        'speed_label': 'speed(RPM)',  # The label carrying the speed readout
        'kv': 500},),  # An argument to pass to the FakeDCMotor
      freq=50,  # Lowering the default frequency because it is just a demo

      # Sticking to default for the other arguments
  )

  # This Grapher displays the real-time emulated speed of the DC motor
  graph = crappy.blocks.Grapher(
      # The names of the labels to plot on the graph
      ('t(s)', 'speed(RPM)'),

      # Sticking to default for the other arguments
  )

  # Linking the Block so that the information is correctly sent and received
  crappy.link(gen, mot)
  crappy.link(mot, graph)

  # This Block provides a clean way to stop the test before it ends
  stop = crappy.blocks.StopButton()

  # Mandatory line for starting the test, this call is blocking
  crappy.start()
