# coding: utf-8

"""
This example demonstrates how a Machine Block drives multiple Actuators at
once. It does not require any specific hardware, but requires pyqtgraph and
PyQt6.

The Machine Block can drive one or more Actuators in speed or position mode,
based on the setpoints it receives from upstream Blocks. It can also retrieve
the current speed and/or position from the driven Actuators and send it to
downstream Blocks.

Here, a Machine Block drives two FakeStepperMotor Actuators in speed mode.
The setpoint is generated by a Generator as a cyclic speed value, and one of
the motors receives an inverted setpoint value so that their behavior is
symmetrical. This behavior is useful, for example, in a tensile test machine
equipped with two motors. Finally, the positions of both motors are sent to a
Grapher Block for display.

After starting this script, observe how both Actuators are successfully being
driven symmetrically. Notice how little the script differs from the basic one
that only drives one Actuator. This script ends after 20 seconds. Click the
stop button to end the demo early.
"""

import crappy

# The name of the labels carrying the setpoints for the two motors
cmd_label = 'cmd'
cmd_label_inv = 'cmd_inv'


def invert_cmd(data):
  """This function inverts the speed command and assigns it to the inverted
  command label.

  It drives both motors symmetrically.
  """

  data[cmd_label_inv] = -data[cmd_label]
  return data


if __name__ == '__main__':

  # This Generator generates the speed command for both Actuators driven by the
  # Machine Block. The command is a cyclic one oscillating between 1 and -1 but
  # remaining at 1 longer, so the position increases overall
  gen = crappy.blocks.Generator(
      # Generating a cyclic signal oscillating between 1 and -1 with a delay of
      # 4 seconds on 1 and 2 seconds on -1
      ({'type': 'Cyclic',
        'value1': 1,
        'value2': -1,
        'condition1': 'delay=4',
        'condition2': 'delay=2',
        'cycles': 3},),
      freq=50,  # Lowering the default frequency because it is just a demo
      cmd_label=cmd_label,  # The label carrying the speed command

      # Sticking to default for the other arguments
  )

  # This Machine Block drives two FakeStepperMotor Actuators at once. One of
  # them receives an inverted speed setpoint, so its behavior is symmetrical
  # to that of the other motor. The positions of both motors are sent to the
  # Grapher Block for display
  mot = crappy.blocks.Machine(
      # Listing the Actuators to drive and their characteristics
      # Only the setpoint and readout labels differ between them
      ({'cmd_label': cmd_label,
        'position_label': 'pos_mot_1(mm)'},
       {'cmd_label': cmd_label_inv,
        'position_label': 'pos_mot_2(mm)'}),
      # These values are common to both Actuators, so they are given here to
      # avoid repetitions
      common={'type': 'FakeStepperMotor',
              'mode': 'speed'},
      freq=50,  # Lowering the default frequency because it is just a demo

      # Sticking to default for the other arguments
  )

  # This Grapher displays the real-time position of both Actuators driven by
  # the Machine Block. Notice how the curves are symmetric.
  graph = crappy.blocks.Grapher(
      # The names of the labels to plot on the graph
      ('t(s)', 'pos_mot_1(mm)'), ('t(s)', 'pos_mot_2(mm)')

      # Sticking to default for the other arguments
  )

  # Linking the Block so that the information is correctly sent and received
  # The modifier on the Link from the Generator to the Machine inverts the
  # speed command for one motor
  crappy.link(gen, mot, modifier=invert_cmd)
  crappy.link(mot, graph)

  # This Block provides a clean way to stop the test before it ends
  stop = crappy.blocks.StopButton()

  # Mandatory line for starting the test, this call is blocking
  crappy.start()
