# coding: utf-8

"""
This example demonstrates the use of the Sink Block. It requires neither
hardware nor any specific Python modules to run.

The Sink Block discards any data it receives and does nothing more. It is
mainly intended for debugging or as a placeholder for a Block that has not yet
been added while prototyping a script. Admittedly, it is not the most useful
Block, but come on, it took five minutes to write.

Here, the Sink Block discards the data it receives from a Generator Block. And
that's it.

After starting this script, watch how really nothing happens as the generated
data is immediately discarded. In the console, you can still see that the Sink
Block is alive as it displays its looping frequency. This script ends after
17 seconds. Click the stop button to end the demo early.
"""

import crappy

if __name__ == '__main__':

  # This Generator Block outputs a Constant signal for the Sink to ignore.
  gen = crappy.blocks.Generator(
      # Generating a constant value of 0 during 15 seconds
      ({'type': 'Constant', 'condition': 'delay=15', 'value': 0},),
      cmd_label='cmd',  # The label carrying the generated value
      freq=50,  # Lowering the default frequency because it's just a demo
      spam=True,  # Sending a value at each loop

      # Sticking to default for the other arguments
  )

  # This Sink Block receives the data generated by the Generator Block, and
  # does absolutely nothing with it. It only displays its own looping
  # frequency, so that you can see it's not just dead
  sink = crappy.blocks.Sink(
      display_freq=True,  # Displaying the looping frequency to show there's
      # some activity

      # Sticking to default for the other arguments
  )

  # Linking the Block so that the information is correctly sent and received
  crappy.link(gen, sink)

  # This Block provides a clean way to stop the test before it ends
  stop = crappy.blocks.StopButton()

  # Mandatory line for starting the test, this call is blocking
  crappy.start()
