"""Structured hardware compatibility information.

The API docstrings remain the detailed reference. This inventory only records
the fields needed to discover a driver and understand its maintenance and
verification status.
"""

HARDWARE = (
  {"name": "Basler Ironman Camera Link",
   "object": "crappy.camera.cameralink.BaslerIronmanCameraLink",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux",),
   "transport": ("Camera Link", "PCIe"),
   "dependencies": ("Silicon Software SDK", "local C extension"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record is available.",
   "example": None},

  {"name": "Camera GStreamer",
   "object": "crappy.camera.CameraGstreamer",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Video device", "custom pipeline"),
   "dependencies": ("GStreamer", "PyGObject"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "verified",
   "verified_on": "2026-09-22",
   "verification_details": "Verified on Ubuntu 24.04.",
   "example": None},

  {"name": "Camera OpenCV",
   "object": "crappy.camera.CameraOpencv",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Video device",),
   "dependencies": ("opencv-python",),
   "backends": (),
   "maintenance": "maintained",
   "verification": "verified",
   "verified_on": "2026-09-22",
   "verification_details": "Verified on Ubuntu 24.04.",
   "example": None},

  {"name": "Fake Camera",
   "object": "crappy.camera.FakeCamera",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Any",),
   "transport": ("Software-generated images",),
   "dependencies": (),
   "backends": (),
   "maintenance": "maintained",
   "verification": "software-only",
   "verified_on": None,
   "verification_details": "No physical hardware is used.",
   "example": "examples/vision_blocks/camera_basic_display.py"},

  {"name": "File Reader",
   "object": "crappy.camera.FileReader",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Any",),
   "transport": ("Image files",),
   "dependencies": ("SimpleITK or opencv-python",),
   "backends": ("SimpleITK", "OpenCV"),
   "maintenance": "maintained",
   "verification": "software-only",
   "verified_on": None,
   "verification_details": "No physical hardware is used.",
   "example": None},

  {"name": "JAI GO-5000C-PMCL",
   "object": "crappy.camera.cameralink.JaiGO5000CPMCL",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux",),
   "transport": ("Camera Link", "PCIe"),
   "dependencies": ("Silicon Software SDK", "local C extension"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record is available.",
   "example": None},

  {"name": "JAI GO-5000C-PMCL 8 bits",
   "object": "crappy.camera.cameralink.JaiGO5000CPMCL8Bits",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux",),
   "transport": ("Camera Link", "PCIe"),
   "dependencies": ("Silicon Software SDK", "local C extension"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record is available.",
   "example": None},

  {"name": "Raspberry Pi Camera 2",
   "object": "crappy.camera.RaspberryPiCamera2",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Raspberry Pi OS",),
   "transport": ("CSI",),
   "dependencies": ("picamera2", "libcamera", "opencv-python"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Hasn't been tested since 2025.",
   "example": None},

  {"name": "Webcam",
   "object": "crappy.camera.Webcam",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB or integrated video device",),
   "dependencies": ("opencv-python",),
   "backends": (),
   "maintenance": "maintained",
   "verification": "verified",
   "verified_on": "2026-09-22",
   "verification_details": "Tested on Ubuntu 24.04 and Windows 11.",
   "example": "examples/blocks/camera/camera_basic_webcam.py"},

  {"name": "Xi API",
   "object": "crappy.camera.XiAPI",
   "kind": "Camera",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("XIMEA camera interface",),
   "dependencies": ("XIMEA SDK", "ximea"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Not formally tested since 2024, but used "
                           "regularly in lab experiments.",
   "example": None},

  {"name": "Camera gPhoto2",
   "object": "crappy.collection.camera.gphoto2_camera.CameraGPhoto2",
   "kind": "Camera",
   "distribution": "collection",
   "platforms": ("Linux",),
   "transport": ("USB",),
   "dependencies": ("gphoto2", "libgphoto2", "Pillow"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Verified when it was first introduced but not "
                           "used since then.",
   "example": None},

  {"name": "Raspberry Pi Camera",
   "object": (
     "crappy.collection.camera.raspberry_pi_camera.RaspberryPiCamera"),
   "kind": "Camera",
   "distribution": "collection",
   "platforms": ("Raspberry Pi OS Buster", "Bullseye legacy camera mode"),
   "transport": ("CSI",),
   "dependencies": ("picamera", "opencv-python"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Hasn't been tested since 2023.",
   "example": None},

  {"name": "Seek Thermal Pro",
   "object": "crappy.collection.camera.seek_thermal_pro.SeekThermalPro",
   "kind": "Camera",
   "distribution": "collection",
   "platforms": ("Linux",),
   "transport": ("USB",),
   "dependencies": ("pyusb",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Hasn't been tested since at least 2023.",
   "example": None},

  {"name": "ADS1115",
   "object": "crappy.inout.ADS1115",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Raspberry Pi OS", "Blinka-supported boards"),
   "transport": ("I2C",),
   "dependencies": ("smbus2", "Adafruit-Blinka",
                    "adafruit-circuitpython-ads1x15"),
   "backends": ("Pi4", "blinka"),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "DAQmx",
   "object": "crappy.inout.DAQmx",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("National Instruments DAQ interface",),
   "dependencies": ("NI-DAQmx C driver", "PyDAQmx"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Fake InOut",
   "object": "crappy.inout.FakeInOut",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Any",),
   "transport": ("Software memory usage",),
   "dependencies": ("psutil",),
   "backends": (),
   "maintenance": "maintained",
   "verification": "software-only",
   "verified_on": None,
   "verification_details": "No physical hardware is used.",
   "example": "examples/blocks/ioblock/ioblock_basic.py"},

  {"name": "GPIO PWM",
   "object": "crappy.inout.GPIOPWM",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Raspberry Pi OS",),
   "transport": ("GPIO",),
   "dependencies": ("RPi.GPIO",),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "GPIO Switch",
   "object": "crappy.inout.GPIOSwitch",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Raspberry Pi OS", "Blinka-supported boards"),
   "transport": ("GPIO",),
   "dependencies": ("RPi.GPIO", "Adafruit-Blinka"),
   "backends": ("Pi4", "blinka"),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Labjack T7",
   "object": "crappy.inout.LabjackT7",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB", "Ethernet", "Wi-Fi"),
   "dependencies": ("LabJack LJM", "labjack-ljm"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Not formally tested recently but used regularly "
                           "in lab experiments.",
   "example": "examples/other_examples/labjack_t7.py"},

  {"name": "Labjack T7 Streamer",
   "object": "crappy.inout.T7Streamer",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB", "Ethernet", "Wi-Fi"),
   "dependencies": ("LabJack LJM", "labjack-ljm"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Not formally tested recently but used regularly "
                           "in lab experiments.",
   "example": "examples/other_examples/labjack_t7_stream.py"},

  {"name": "MPRLS",
   "object": "crappy.inout.MPRLS",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Raspberry Pi OS", "Blinka-supported boards"),
   "transport": ("I2C",),
   "dependencies": ("smbus2", "RPi.GPIO", "Adafruit-Blinka",
                    "adafruit-circuitpython-mprls"),
   "backends": ("Pi4", "blinka"),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "NAU7802",
   "object": "crappy.inout.NAU7802",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Raspberry Pi OS",),
   "transport": ("I2C",),
   "dependencies": ("smbus2", "RPi.GPIO"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "NI DAQmx",
   "object": "crappy.inout.NIDAQmx",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("National Instruments DAQ interface",),
   "dependencies": ("NI-DAQmx driver", "nidaqmx"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Phidget Wheatstone Bridge",
   "object": "crappy.inout.PhidgetWheatstoneBridge",
   "kind": "InOut",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB VINT Hub", "network VINT Hub"),
   "dependencies": ("Phidget22 drivers", "Phidget22"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Not formally tested recently but used regularly "
                           "in lab experiments.",
   "example": None},

  {"name": "Agilent 34420A",
   "object": "crappy.collection.inout.agilent_34420A.Agilent34420a",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Comedi",
   "object": "crappy.collection.inout.comedi.Comedi",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux",),
   "transport": ("Comedi device interface",),
   "dependencies": ("libcomedi", "local ctypes binding"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Eurotherm EPC3008",
   "object": (
     "crappy.collection.inout.eurotherm_EPC3008.EurothermEPC3008"),
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial", "Modbus RTU"),
   "dependencies": ("pymodbus", "pyserial"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Flow Controller Alicat",
   "object": (
     "crappy.collection.inout.flow_controller_alicat.FlowControllerAlicat"),
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial RS-485", "Modbus RTU"),
   "dependencies": ("pymodbus", "pyserial"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Kollmorgen AKD PDMM",
   "object": (
     "crappy.collection.inout.kollmorgen_akd_pdmm.KollmorgenAKDPDMM"),
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Ethernet", "Modbus TCP"),
   "dependencies": ("pymodbus",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Labjack UE9",
   "object": "crappy.collection.inout.labjack_ue9.LabjackUE9",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB", "Ethernet"),
   "dependencies": ("LabJackPython",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "MCP9600",
   "object": "crappy.collection.inout.mcp9600.MCP9600",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Raspberry Pi OS", "Blinka-supported boards"),
   "transport": ("I2C",),
   "dependencies": ("smbus2", "Adafruit-Blinka",
                    "adafruit-circuitpython-busdevice",
                    "adafruit-circuitpython-mcp9600"),
   "backends": ("Pi4", "blinka"),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "OpSens HandySens",
   "object": "crappy.collection.inout.opsens_handysens.HandySens",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "PiJuice",
   "object": "crappy.collection.inout.pijuice_hat.PiJuice",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Raspberry Pi OS",),
   "transport": ("I2C",),
   "dependencies": ("smbus2", "pijuice"),
   "backends": ("Pi4", "pijuice"),
   "maintenance": "legacy",
   "verification": "verified",
   "verified_on": "2026-03-26",
   "verification_details": "Tested on a Raspberry Pi 4.",
   "example": None},

  {"name": "Sager SG-GS1700",
   "object": "crappy.collection.inout.sager_sg_gs1700.SagerSG_GS1700",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial", "AIBUS"),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Sim868",
   "object": "crappy.collection.inout.sim868.Sim868",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial", "cellular network"),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "verified",
   "verified_on": "2026-03-26",
   "verification_details": "Tested on a Raspberry Pi 4.",
   "example": None},

  {"name": "Spectrum M2I 4711",
   "object": (
     "crappy.collection.inout.spectrum_m2i4711.SpectrumM2I4711"),
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Linux", "Windows"),
   "transport": ("PCIe",),
   "dependencies": ("Spectrum driver", "local ctypes binding"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Waveshare AD/DA",
   "object": "crappy.collection.inout.waveshare_ad_da.WaveshareADDA",
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Raspberry Pi OS",),
   "transport": ("SPI", "GPIO"),
   "dependencies": ("spidev", "RPi.GPIO"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Waveshare High Precision",
   "object": (
     "crappy.collection.inout.waveshare_high_precision."
     "WaveshareHighPrecision"),
   "kind": "InOut",
   "distribution": "collection",
   "platforms": ("Raspberry Pi OS",),
   "transport": ("SPI", "GPIO"),
   "dependencies": ("spidev", "RPi.GPIO"),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Fake DC Motor",
   "object": "crappy.actuator.FakeDCMotor",
   "kind": "Actuator",
   "distribution": "core",
   "platforms": ("Any",),
   "transport": ("Software simulation",),
   "dependencies": (),
   "backends": (),
   "maintenance": "maintained",
   "verification": "software-only",
   "verified_on": None,
   "verification_details": "No physical hardware is used.",
   "example": "examples/blocks/machine/machine_basic.py"},

  {"name": "Fake Stepper Motor",
   "object": "crappy.actuator.FakeStepperMotor",
   "kind": "Actuator",
   "distribution": "core",
   "platforms": ("Any",),
   "transport": ("Software simulation",),
   "dependencies": (),
   "backends": (),
   "maintenance": "maintained",
   "verification": "software-only",
   "verified_on": None,
   "verification_details": "No physical hardware is used.",
   "example": "examples/blocks/machine/machine_speed.py"},

  {"name": "JVL Mac140",
   "object": "crappy.actuator.JVLMac140",
   "kind": "Actuator",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Kollmorgen ServoStar 300",
   "object": "crappy.actuator.ServoStar300",
   "kind": "Actuator",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Phidget Stepper4A",
   "object": "crappy.actuator.Phidget4AStepper",
   "kind": "Actuator",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB VINT Hub", "network VINT Hub"),
   "dependencies": ("Phidget22 drivers", "Phidget22"),
   "backends": (),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "Not formally tested recently but used regularly "
                           "in lab experiments.",
   "example": None},

  {"name": "Pololu Tic",
   "object": "crappy.actuator.PololuTic",
   "kind": "Actuator",
   "distribution": "core",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("USB",),
   "dependencies": ("pyusb", "PyYAML", "Pololu ticcmd"),
   "backends": ("USB", "ticcmd"),
   "maintenance": "maintained",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Adafruit DC Motor Hat",
   "object": (
     "crappy.collection.actuator.adafruit_dc_motor_hat.DCMotorHat"),
   "kind": "Actuator",
   "distribution": "collection",
   "platforms": ("Raspberry Pi OS", "Blinka-supported boards"),
   "transport": ("I2C",),
   "dependencies": ("smbus2", "Adafruit-Blinka",
                    "adafruit-circuitpython-motorkit"),
   "backends": ("Pi4", "blinka"),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Newport TRA6PPD",
   "object": "crappy.collection.actuator.newport_tra6ppd.NewportTRA6PPD",
   "kind": "Actuator",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Oriental ARD-K",
   "object": "crappy.collection.actuator.oriental_ard_k.OrientalARDK",
   "kind": "Actuator",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None},

  {"name": "Schneider MDrive 23",
   "object": (
     "crappy.collection.actuator.schneider_mdrive_23.SchneiderMDrive23"),
   "kind": "Actuator",
   "distribution": "collection",
   "platforms": ("Linux", "Windows", "macOS"),
   "transport": ("Serial",),
   "dependencies": ("pyserial",),
   "backends": (),
   "maintenance": "legacy",
   "verification": "unverified",
   "verified_on": None,
   "verification_details": "No dated test record.",
   "example": None}
)
