# coding: utf-8

from .test_advanced_tutorials import TestAdvancedTutorialDownloads
from .test_custom_object_tutorials import TestCustomObjectTutorialDownloads
from .test_getting_started import TestGettingStartedDownloads
